spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    initialization-mode: always
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
